#!/bin/bash
# Ethara Task Manager - Railway Deployment Script
# Run this after pushing to GitHub and setting up Railway project

echo "Ethara Task Manager - Railway Deployment Steps"
echo "================================================"
echo ""
echo "Step 1: Go to https://railway.app and sign in"
echo "Step 2: Click 'Create New Project'"
echo "Step 3: Select 'Deploy from GitHub repo'"
echo "Step 4: Choose: Ridhimaaaa29/Ethara-Task-Manager"
echo "Step 5: Railway will auto-detect Node.js"
echo ""
echo "Step 6: Add PostgreSQL Database"
echo "  - Click 'New' in Railway dashboard"
echo "  - Search and select PostgreSQL"
echo "  - Railway auto-generates DATABASE_URL"
echo ""
echo "Step 7: Set Environment Variables"
echo "  Go to Variables tab of your Next.js service:"
echo ""
echo "  DATABASE_URL = (auto-populated from PostgreSQL)"
echo "  AUTH_SECRET = (generate random 32-char string below)"
echo ""
echo "Generate AUTH_SECRET (copy the output):"
openssl rand -base64 32
echo ""
echo "Step 8: Deploy"
echo "  - Click Deploy button"
echo "  - Wait for build to complete (~3-5 minutes)"
echo ""
echo "Step 9: Run Database Migrations"
echo "  Option A - Railway CLI:"
echo "    npm install -g @railway/cli"
echo "    railway login"
echo "    railway link"
echo "    railway run npx prisma migrate deploy"
echo ""
echo "  Option B - Dashboard:"
echo "    Check deploy logs for Prisma output"
echo ""
echo "Step 10: Access Live App"
echo "  - Railway provides your public URL"
echo "  - First signup creates admin account"
echo "  - Start creating projects!"
echo ""
echo "================================================"
echo "Need help? Check DEPLOYMENT.md or Railway docs"
